### ISSUE TITLE
Play with synthesis parameters

### ISSUE THREAD

**Issue by ryangawei** [24HRsEscaption/5500-project#24]
Things to figure out:

1. The reasonable range of parameters
2. What happen if negative values are provided

**Comment by KarishmaVadsaria** [comment]
Parameters(Trying negative values):

1) Duration:
Giving a negative value for the duration (-1) throws a runtime error [RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0, 128] because the unspecified dimension size -1 can be any value and is ambiguous]

2) Energy:
The negative values are accepted for the energy parameter but it does not make much difference in the audio it sounds similar for the value -10 as well as -50.

3) Pitch:
I tried negative values of the pitch like -10 to -50 but it sounds like an old woman trying to speak on the lower pitch, we won't need this so I think we can ignore the negative values.
